### PR TITLE
changing braindecode documentation theme

### PR DESCRIPTION
**Pull request by bruAristimunha**
Hello @robintibor!

As agreed in the PR, the contribution to the braindecode theme change.

### CODE REVIEW

**Comment by robintibor** [comment]
Hm, might be better to directly push into my PR at braindecode main repo (by pushing directly into my branch)? Was not aware need to give you rights for that, but now I gave you maintainer status at github.com/braindecode/braindecode/ and then you should be able to I think? How do you think @bruAristimunha

**Comment by bruAristimunha** [comment]
Could be a solution. I will try.

**Comment by robintibor** [comment]
hm so did it work or not? saw some mail with your comment, but you deleted again I assume? :) also invited you to this repo now in case you need it

**Comment by bruAristimunha** [comment]
Yes, I deleted it. I was trying to discover a way to merge more elegantly, but, anyway, let's go for the quickest solution.

**Pull request merged**
